version: '3.1'

services:

  mariadb-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3307:3306"