resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
    instances:
      items:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
      instances:
        items:
          base-config: default